### ISSUE TITLE
mfdb_plyr_sample error

### ISSUE THREAD

**Issue by niafall** [mareframe/mfdb#57] opened 2019-05-30 16:24 UTC
I'm trying to set some initial conditions for a gadget model by sampling from my `mdb `using `mfdb_plyr_sample`.

I'm using code similar to that used in [this example](https://github.com/fishvice/gadget-models/blob/master/06-ling/00-setup/setup-model.R), which worked for me previously.

```
init.sigma <- 
  mfdb_dplyr_sample(mdb) %>% 
  dplyr::filter(species == defaults$species, age >0, !is.na(length), sampling_type=="EXA")  %>% 
  dplyr::select(age,length) %>% 
  dplyr::collect(n=Inf) %>% 
  dplyr::group_by(age) %>% 
  dplyr::summarise(ml=mean(length,na.rm=TRUE), ms=sd(length,na.rm=TRUE))
```

Now I get the following error:

```
Error in UseMethod("escape") : 
  no applicable method for 'escape' applied to an object of class "c('mfdb_group', 'mfdb_aggregate')"
```

Any advice on what may be causing the issue?

**Comment by lentinj** [comment] 2019-05-31 16:52
Where are you running this code / which dplyr version are you using? This could be a ``dplyr`` upgrade causing problems, and I upgraded ~everything on the mfdb-server a few weeks ago.

**Comment by niafall** [comment] 2019-05-31 16:57
Here is my session info:

```
R version 3.6.0 (2019-04-26)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8    LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] mfdb_5.2-0      plotrix_3.7-5   gridExtra_2.3   pander_0.6.3    Rgadget_0.5     forcats_0.4.0   stringr_1.4.0  
 [8] dplyr_0.8.1     purrr_0.3.2     readr_1.3.1     tidyr_0.8.3     tibble_2.1.1    ggplot2_3.1.1   tidyverse_1.2.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1        cellranger_1.1.0  pillar_1.4.1      compiler_3.6.0    plyr_1.8.4        tools_3.6.0       digest_0.6.19    
 [8] jsonlite_1.6      lubridate_1.7.4   gtable_0.3.0      nlme_3.1-139      lattice_0.20-38   pkgconfig_2.0.2   rlang_0.3.4      
[15] DBI_1.0.0         cli_1.1.0         rstudioapi_0.10   RPostgreSQL_0.6-2 yaml_2.2.0        haven_2.1.0       withr_2.1.2      
[22] xml2_1.2.0        httr_1.4.0        generics_0.0.2    hms_0.4.2         grid_3.6.0        tidyselect_0.2.5  glue_1.3.1       
[29] R6_2.4.0          readxl_1.3.1      modelr_0.1.4      magrittr_1.5      backports_1.1.4   scales_1.0.0      rvest_0.3.4      
[36] assertthat_0.2.1  colorspace_1.4-1  logging_0.9-107   stringi_1.4.3     lazyeval_0.2.2    munsell_0.5.0     broom_0.5.2      
[43] crayon_1.3.4  
```

**Comment by lentinj** [comment] 2019-06-03 13:44
Your mfdb version is somewhat old and will be missing https://github.com/mareframe/mfdb/commit/6041deb73fd5feadecbe99c58e6c7e2536191708 which is probably the cause.

So either upgrade to mfdb 6.0-0 or I can release a 5.3-0 that includes it.

**Comment by niafall** [comment] 2019-06-03 21:36
Ah, thank you, @lentinj - I had copied the code directly from the README where it says:

`devtools::install_github("mareframe/mfdb", ref = "5.x")`

I will update and try that.

**Comment by niafall** [comment] 2019-06-03 22:27
I'm still getting the error with `mfdb_6.0-0`. Is there anything else I should try?

**Comment by lentinj** [comment] 2019-06-04 09:30
Actually, looking at the error message, dplyr is trying to do something with an ``mfdb_group()`` class. They shouldn't exist by the time dplyr gets to do it's thing.

Is it possible that age or length are variables defined as some kind of ``mfdb_group()``, and dplyr is using these when it should be referring to the columns?

**Comment by niafall** [comment] 2019-06-04 10:45
I can get data from my mdb using:

```
init.sigma <- mfdb_dplyr_sample(mdb)
```

This returns:

```
# Source:   lazy query [?? x 20]
# Database: postgres 10.0.8 [niall@/var/run/postgresql:5432/mf]
   sample_id  year month   age length length_var length_min weight weight_var count institute gear  sex  
       <int> <int> <int> <dbl>  <dbl>      <dbl>      <int>  <dbl>      <dbl> <dbl> <chr>     <chr> <chr>
 1         1  1985     1    NA     26         NA         NA     NA         NA   180 FRS       NA    U    
 2         2  1985     1    NA     33         NA         NA     NA         NA    12 FRS       NA    U    
 3         3  1985     1    NA     29         NA         NA     NA         NA     2 FRS       NA    U    
 4         4  1985     1    NA     24         NA         NA     NA         NA   350 FRS       NA    U    
 5         5  1985     1    NA     32         NA         NA     NA         NA    11 FRS       NA    U    
 6         6  1985     1    NA     42         NA         NA     NA         NA    16 FRS       NA    U    
 7         7  1985     1    NA     39         NA         NA     NA         NA    26 FRS       NA    U    
 8         8  1985     1    NA     30         NA         NA     NA         NA     2 FRS       NA    U    
 9         9  1985     1    NA     22         NA         NA     NA         NA     1 FRS       NA    U    
10        10  1985     1    NA     50         NA         NA     NA         NA     1 FRS       NA    U    
# … with more rows, and 7 more variables: maturity_stage <chr>, species <chr>, areacell <chr>,
#   sampling_type <chr>, data_source <chr>, tow <chr>, vessel <chr>
```

So it looks like age and length are defined properly? However, if I try to call `init.sigma$x` it returns `NULL`.

**Comment by bthe** [comment] 2019-06-04 10:53
You need to collect the results from the database. Something like this should work:

```
init.sigma <- mfdb_dplyr_sample(mdb) %>% collect(n=Inf)
```

**Comment by niafall** [comment] 2019-06-04 12:04
This returns the following error:

```
Error in UseMethod("escape") : 
  no applicable method for 'escape' applied to an object of class "c('mfdb_group', 'mfdb_aggregate')"
In addition: Warning messages:
1: Missing values are always removed in SQL.
Use `MIN(x, na.rm = TRUE)` to silence this warning
This warning is displayed only once per session. 
2: Missing values are always removed in SQL.
Use `SUM(x, na.rm = TRUE)` to silence this warning
This warning is displayed only once per session.
```

**Comment by niafall** [comment] 2019-06-04 14:25
Apologies, I didn't realise the previous comment was @bthe 

I included collect `(n=Inf)` in the original code.

**Comment by lentinj** [comment] 2019-06-06 10:16
In general, this seems like a good way to reproduce the error you're getting:

```
> argh <- mfdb_group(2)
> mfdb_dplyr_sample(mdb) %>% dplyr::filter(species == 'COD', argh == 22)
Error in UseMethod("escape") :
  no applicable method for 'escape' applied to an object of class "c('mfdb_group', 'mfdb_aggregate')"
```

i.e both...

* Applying a dplyr function on a column that doesn't exist
* The non-existent column name is defined as an mfdb_group

I'd suggest picking bits off your example above until it starts working, then we can go from there.

**Comment by niafall** [comment] 2019-07-09 10:36
It appears the issue comes down to using `species == defaults$species` in the `dplyr::filter`. Replacing this with the species reference, e.g. `"HAD"` for haddock, results in a successful query. This is despite the fact that `defaults$species` is the character string `"HAD"`. Any idea why this might be happening?

**Comment by lentinj** [comment] 2019-07-10 08:03
Could ``defaults$species`` actually be a factor, or something else that just looks string-ish? Does an ``as.character(defaults$species)`` help? What does ``str(defaults$species)`` look like?

**Comment by bthe** [comment] 2019-07-10 17:25
This might also be an issue with dplyr, we have had some random issues with passing variables to database queries.

On 10 Jul 2019, at 08:03, Jamie Lentin <notifications@github.com<mailto:notifications@github.com>> wrote:


Could defaults$species actually be a factor, or something else that just looks string-ish? Does an as.character(defaults$species) help? What does str(defaults$species) look like?

**Comment by niafall** [comment] 2019-07-10 19:59
`defaults$species` does indeed appear to be a character string:

```
> str(defaults$species)
 chr "HAD"
> is.factor(defaults$species)
[1] FALSE
> class(defaults$species)
[1] "character"
```

Using `as.character(defaults$species)` thus doesn't make any difference. Perhaps it is a dplyr issue as @bthe suggested?

**Comment by lentinj** [comment] 2019-07-11 09:51
Yeah, it could be a naming clash in one of the dplyr environments that get laid on top. You could try assigning to a randomly-named variable first and see if that helps.

**Comment by bthe** [comment] 2019-07-11 15:05
Could using the local function solve this: https://dbplyr.tidyverse.org/reference/partial_eval.html

On 11 Jul 2019, at 09:51, Jamie Lentin <notifications@github.com<mailto:notifications@github.com>> wrote:


Yeah, it could be a naming clash in one of the dplyr environments that get laid on top. You could try assigning to a randomly-named variable first and see if that helps.

**Comment by niafall** [comment] 2019-07-12 11:00
I tried `partial_eval `but that returns the same error. The problem appears to be passing the species name as a list element. At least we have found out how to avoid the problem!

**Comment by bthe** [comment] 2020-02-10 13:45
We have had this issue cropping up in various instances in the past year after a change in `dplyr` last summer and in almost all cases this has been solved by wrapping `local` around variable names you want to pass into the sql query, e.g in your case you would do: 

```
... %>%
filter(species == local(default$species)) %>% 
...
```
I think we can close this issue for now.

**Closed as completed by bthe** 2020-02-10 13:45 UTC
